
# SEO settings
title: Katty Lein
title2: Katty Lein
description: """"
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://yoyoyokatty.github.io # site url
baseurl: NULL

google_analytics: UA-XXXXX-XX
repo: http://github.com/heiswayi/thinkspace
disqus_shortname: "heiswayi"
twitter_username: "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Katty Lein"
  job      : "Data Science Immersive Student at General Assembly"
  bio      : ""
  thumb    : /images/author.jpg
  email    : katty.lein@gmail.com
  url      : http://yoyoyokatty.github.io
  github   : n/a
  twitter  : n/a
  facebook : n/a
  linkedin : https://www.linkedin.com/in/kattylein

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "n/a"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
